<?php

/**
 * @var $block \MagicToolbox\MagicZoom\Block\Template
 */

$id = $block->getData('id');
$mainHTML = $block->getData('mainHTML');
$selectorsArray = $block->getData('selectorsArray');
$selectorMaxWidth = $block->getData('selectorMaxWidth');
$additionalClasses = $block->getData('additionalClasses');
$scrollOptions = $block->getData('scrollOptions');
$thumbSwitcherOptions = $block->getData('thumbSwitcherOptions');
?>
<div class="MagicToolboxContainer selectorsTop minWidth"<?= $thumbSwitcherOptions ?>>
<?php
if (count($selectorsArray)) {
?>
    <div class="MagicToolboxSelectorsContainer<?php if (count($selectorsArray) == 1) echo ' hidden-container' ?>">
        <div id="MagicToolboxSelectors<?= $id ?>" class="<?= $additionalClasses ?>"<?= $scrollOptions ?>>
        <?= join("\n\t\t", $selectorsArray); ?>
        </div>
    </div>
<?php
}
?>
    <?= $mainHTML; ?>
</div>
